### ISSUE TITLE
split the examples to modules?

### ISSUE THREAD

**Issue by geekplux** [d3-node/d3-node#10]
Hi,

Thanks for your awesome repo. I have a small tip that to split the examples to modules. It makes d3-node more scalable and minimal. Every example module can published to the npm which can be maintained independent, and more people could create the example. You also can have your own organization as a container to list these module.

Just my advice. thanks again 👍

**Comment by bradoyler** [comment]
Hm. I kinda like that idea... 👍

**Comment by bradoyler** [comment]
Created: https://github.com/d3-node
Lmk if you like to contribute an example

**Comment by geekplux** [comment]
Yeah, of course I want to contribute to it. 
In fact, I'm developing a plugin for markdown and I need to build some basic example(like bar, line and pie) by d3-node.

**Comment by bradoyler** [comment]
https://github.com/d3-node/d3node-barchart 
I'll get the rest added in the next couple days. 🍻

**Comment by geekplux** [comment]
ok, I'll help you.
