### ISSUE TITLE
.svgString() automatically lowercases tags? 

### ISSUE THREAD

**Issue by KingZee** [d3-node/d3-node#13]
To reproduce, insert any element with a tag containing uppercase using selection.html(), and print it with the svg.svgString() function. 

This is a sample output I'm getting : 
`<svg xmlns="http://www.w3.org/2000/svg" width="500" height="50"><radialgradient id="grad1" x1="10%" y1="10%" x2="80%" y2="90%"> <stop offset="0%" style="stop-color:#627AAD;stop-opacity:0.9"></stop> <stop offset="100%" style="stop-color:#3B5998;stop-opacity:0.9"></stop> </radialgradient><circle cx="25" cy="25" r="5" fill="url(#grad1)"></circle><circle cx="75" cy="25" r="10" fill="url(#grad1)"></circle><circle cx="125" cy="25" r="15" fill="url(#grad1)"></circle><circle cx="175" cy="25" r="20" fill="url(#grad1)"></circle><circle cx="225" cy="25" r="25" fill="url(#grad1)"></circle></svg>`

Because svgString() lowercases the g in `radialGradient`, it will break the file, and the above svg does not get rendered.

You can take the above svg and change the `radialgradient` to `radialGradient`, it renders correctly.

**Comment by KingZee** [comment]
The reason for this seems to go way beyond d3-node and d3 itself... 
I'm closing it here. Refer to a simiar issue in : https://github.com/tmpvar/jsdom/issues/620

**Comment by bradoyler** [comment]
@KingZee great find. Thx.

**Comment by bradoyler** [comment]
@KingZee if you could share the d3 script you were using to produce this issue, it was be appreciated. 
I'm wondering if there's a monkey patch d3-node could apply for these scenarios.

**Comment by KingZee** [comment]
```
const d3n = new D3Node();
var svg = d3n.createSVG()
    .style("width",800)
    .style("height",480)
    .attr("preserveAspectRatio","true");

svg.append("radialGradient");
```
Here's a part of my code.

So since svgString() is equivalent of getting the svg.node().outerHTML, and HTML isn't case sensitive, the output tags are all lowercased, I have managed to tweak this by instead of getting the HTML using svgString(), I parse the node directly using xmlserializer, so something like : 

`require('xmlserializer').serializeToString(svg.node())`

The output will take into account case sensitivity. Since this adds dependency to xmlserializer it's up to you if you want to add this fix, I couldn't find another way to work around this. Cheers.

**Comment by bradoyler** [comment]
Ok, I'm going to create a fix and a test for this.

**Comment by bradoyler** [comment]
This may be resolved soon via jsdom with https://github.com/tmpvar/jsdom/issues/1368

**Comment by bradoyler** [comment]
@KingZee `d3-node@1.0.1` should no longer have this issue.
