### ISSUE TITLE
Any benefits of using this over D3 in node?

### ISSUE THREAD

**Issue by techslides** [d3-node/d3-node#19]
D3 can already run in node (var d3 = require("d3");) so what benefits does this library add?

**Comment by geekplux** [comment]
Generally, `ReferenceError: document is not defined` error would arise if you use d3 in node

**Comment by darrinholst** [comment]
Last time I used d3 on the server there was an ugly jsdom hack to get a dom. Haven't looked to see how this library does it, but anything to abstract that away would be beneficial imo.

**Comment by bradoyler** [comment]
There's a few benefits: 
- easily inject/embed stylesheets into the svg
- patches an xml casing issue with jsdom, see https://github.com/d3-node/d3-node/blob/master/index.js#L8
- easily output html (w/ container) or just the svg
- the `createSVG()` method will ensure svg is create with proper namespace which can cause issues with converting to PNG.
