### ISSUE TITLE
Add new append

### ISSUE THREAD

**Issue by danielsalles** [d3-node/d3-node#21]
I'm trying to do this using d3-node to speed it up. But I'm encountering some issues, I'm basically trying to use the techanJS lib for creating candlestick graphics (http://bl.ocks.org/andredumas/27c4a333b0e0813e093d).
I used d3n.createSVG() for the creation of the first svg. However, it seems that this function only executes and returns nothing. And I'd like to know how I do to give a later append.

Example: 
```
const svg = d3n.createSVG().append('g')
  .attr("width", 50)
  .attr("height", 50)
  .append("circle")
  .attr("cx", 25)
  .attr("cy", 25)
  .attr("r", 25)
  .style("fill", "purple")
```

After being created I can add some new information (append).
For example: `svg.append(...)`

Congratulations on the lib, it looks pretty promising.

**Comment by geekplux** [comment]
thank you report, but I don't know why it returns nothing.  you could have a try to write like the https://github.com/d3-node/d3node-linechart/blob/master/index.js#L33-L37

**Comment by bradoyler** [comment]
@danielsalles In your example, svg will return a [D3 'Selection'](https://github.com/d3/d3-selection).
If you do `console.dir(svg)`, you should get: 
```js
Selection { _groups: [ [ HTMLUnknownElement {} ] ], _parents: [ null ] }
```
then to append, you just do `svg.append('div')` 

finally, to get the svg output, just do: `d3n.svgString()`
