### ISSUE TITLE
Alternative to node-canvas

### ISSUE THREAD

**Issue by bradoyler** [d3-node/d3-node#31]
That Node-canvas dependency is a pain to install and also a pain to test.

**Comment by geekplux** [comment]
I think puppeteer is a better choice. 🌚 What do you think, I would have a try if you agree with me.

**Comment by bradoyler** [comment]
Yes 100% agree. 
It would cover both svg2png AND canvas2png and also have a lot more options for rendering d3 to images.

**Comment by geekplux** [comment]
Aha, I will open a new branch to try puppeteer out this week.

**Comment by bradoyler** [comment]
turns out node-canvas v2 is MUCH nicer than v1.x. resloved this via https://github.com/d3-node/d3-node/commit/d40b1b7f8c1d1
