### ISSUE TITLE
update to latest version of d3?

### ISSUE THREAD

**Issue by hems** [d3-node/d3-node#36]
I'm getting the error

````
.attrs is not a function
````

when trying to simply run:

````javascript
svg.append('rect').attrs({x:10})
````

i believe because this module depends on an older version of d3?

**Comment by geekplux** [comment]
thanks. but what you need maybe this: https://github.com/d3/d3-selection-multi, and:

> This module is not included in the default D3 bundle for parsimony’s sake

**Comment by hems** [comment]
@geekplux thanks for your reply!

I'm AFK at the moment, but I hope that installing the module and requiring it will be enough to add that method to the d3 prototype as it [looks like by reading this](https://github.com/d3/d3-selection-multi/blob/master/index.js)
