### ISSUE TITLE
Can we publish the package as precompiled because npm production builds are failing because module has failed to compile

### ISSUE THREAD

**Issue by atulsingh0913** [d3-node/d3-node#39]
I am trying to use d3-node along with react js to plot chorolpleth maps. But it is not able to compile properly. It is failing because of jsdom dependency not getting resolved properly.

I am getting the following error

```
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/d3-node/node_modules/jsdom/lib/jsdom/living/generated/utils.js:5 
```

Can we have this package pre compiled.

**Comment by bradoyler** [comment]
are you trying to build d3-node for a browser? This project is intended for nodejs and relies on jsdom, for that reason.

**Comment by bradoyler** [comment]
If you're using React & D3 you should go this route: https://medium.com/@zimrick/how-to-create-pure-react-svg-maps-with-topojson-and-d3-geo-e4a6b6848a98

React has its own isomorphic Dom rendering path. So you have to do it the "React way".
