### ISSUE TITLE
Specify that node-canvas dependency is for 1.x branch.

### ISSUE THREAD

**Issue by Amndeep7** [d3-node/d3-node#42]
Should specify in your documentation that the optional node-canvas dependency is for the 1.x branch.  They have moved on to a 2.x branch and one of the breaking changes is that the Canvas constructor is no longer the default export from the module.  Please see [their documentation](https://github.com/Automattic/node-canvas/blob/65ff59a4e982a8c3582aef362d6c07c90ce57d7e/CHANGELOG.md#200).

**Comment by bradoyler** [comment]
@Amndeep7 HTH for now. https://github.com/d3-node/d3-node/commit/8c606567f60affd7367bca8261d099c4c488e2d6

**Comment by Amndeep7** [comment]
Now the code manages to generate a png for me, but it's completely blank presumably due to the fact that I'm running it off of WSL which has no visual component.  This is an issue cause your code and presumably the canvas alternative both probably rely on screenshotting in one form or another to generate the png.  As a double check, I made it print out the svg to the console and that appeared to be correct, so this makes me point my finger at the conversion to png part of the process.

**Comment by bradoyler** [comment]
@Amndeep7 yea, more work needs to be done to improve the png generation process.
See #31

**Comment by Amndeep7** [comment]
Ok, so lemme know if I should move this discussion over to d3node-output / barchart, but imma ask here in the meantime.  Got canvas installed and working on both the linux (wsl) and windows side, but both just resulted in blank pngs.  Removed that dependency and just went at it with your built-in version which for me only works on the windows side cause wsl doesn't let you open graphical applications (i.e. can't open that chromium instance).  This was able to generate the output correctly; however, something seems up with the vertical component of how it displays: it seems like the vertical margin doesn't get applied to the chart.

Here is my code:
```
                const d3nBar = require("d3node-barchart");
                const bar = d3nBar({ "data": commentsperday.rows.slice(0, 7), "width": 1280, "height": 670 });
                console.log(bar.svgString());
                const output = require("d3node-output");
                output("graph", bar, { "width": 1280, "height": 720 });
```

This produces the correct output when I manually correct for the vertical margin (20 from top, 30 from bottom).  If I set the height parameter in d3nBar to also be 720, then the bottom of the chart gets cut off.

Height of 670:
![Height of 670](https://user-images.githubusercontent.com/2015821/49303553-f86e0900-f497-11e8-83e6-2c54af1c0cf3.png)

Height of 720:
![Height of 720](https://user-images.githubusercontent.com/2015821/49303598-176c9b00-f498-11e8-9dfa-e2ed49a08a30.png)

I'm not sure if I'm doing something wrong on my side or if it's a bug.  I was poring over your code last night and wasn't able to figure out what the issue was haha.

**Comment by bradoyler** [comment]
Ah, there seems to be some confusion. Using node-canvas is only needed for a d3 script that use the canvas element.  
As for this issue, seems related to how the svg barchart is scaling with viewBox. This is not super straightforward but I can try to post some examples at a later date if you create an issue in that repo.
Cheers. 🍻
