### ISSUE TITLE
Lib is not compatible with node-canvas 2.5.0

### ISSUE THREAD

**Issue by gitowiec** [d3-node/d3-node#48]
There is missing the static "version" field on the Canvas class. 
I need to hack node-canvas to make it work with d3-node:
```
import * as fs from 'fs';
const D3Node = require('d3-node');
import { Canvas } from 'canvas';
(Canvas as any).version = 1; // monkey patching to make it work with d3-node!

export const getScatterPlot = () => {
  const d3n = new D3Node({canvasModule: Canvas});
  const canvas = d3n.createCanvas(960, 500);
  const context = canvas.getContext('2d');
  canvas.pngStream().pipe(fs.createWriteStream('output.png'));
};
```

**Comment by bradoyler** [comment]
here's the root cause: https://github.com/d3-node/d3-node/blob/master/src/index.js#L82 
I was using the version prop to verify its the Canvas module, but I suppose we can change that.

**Comment by bradoyler** [comment]
Also, this module only supports canvas v1.x, as specified in the README
