### ISSUE TITLE
Add svg to canvas prior to png creation with pngStream()

### ISSUE THREAD

**Issue by charlespourreau** [d3-node/d3-node#50]
Hi
I like d3-node to create inline svg server side with  `d3n.svgString()`
I like d3-node to create png file from canvas server side with `canvas.pngStream(`)
But i'm getting confused how to embed the svg into the canvas prior to the png file creation ... 
Could you please help me to bridge the gap ?
Thanks in advance

**Comment by bradoyler** [comment]
embedding svg into canvas is not possible. Either use canvas or svg to render the chart.

**Comment by charlespourreau** [comment]
@bradoyler thank you for your quick answer.
