### ISSUE TITLE
Upgrade to latest d3 version?

### ISSUE THREAD

**Issue by apowers313** [d3-node/d3-node#60]
I'd like to use this with [force graph](https://github.com/d3/d3-force) but it looks like that was added in [D3 6.0](https://github.com/d3/d3/blob/main/CHANGES.md#changes-in-d3-60) and the current version of D3 is 5.0.

I tried forking and upgrading d3 7.0, but I quickly run into the fact that d3 is now only an ECMAScript modules (i.e. `import`) and not a CommonJS module (e.g. `require`). Trying to fix imports quickly turns into a mess with mocha and eslint.

I'm wondering if anyone has tried this before and gave up? Or if it's still worthwhile to keep going down this path?

**Comment by bradoyler** [comment]
Have u tried using the `d3Module` param which can override the d3 lib that is used? 
see: https://github.com/d3-node/d3-node/blob/master/src/index.js#L24

**Comment by jakemccormick** [comment]
@bradoyler I have submitted a pull request for this, since the latest d3-node does not currently pass npm audit. d3-color has vulnerabilities. It removes support for node 10.

**Comment by bradoyler** [comment]
all deps updated
