### ISSUE TITLE
Upgrade JSDOM version

### ISSUE THREAD

**Issue by jakemccormick** [d3-node/d3-node#64]
The version of jsdom used by this project has a security vulnerability. In order to resolve this currently it looks like d3-node would have to use a more recent version of jsdom.

Any plans to upgrade so npm audit is happy?

Thanks

----

jsdom  <=16.4.0
Severity: moderate
Insufficient Granularity of Access Control in JSDom - https://github.com/advisories/GHSA-f4c9-cqv8-9v98

**Comment by jakemccormick** [comment]
This was fixed by another PR

**Comment by jakemccormick** [comment]
Done

**Comment by bradoyler** [comment]
all deps updated
